site_name: Louis' Game Reviews
nav:
  - Home: index.md
  - Ranked by Score: scores.md
  - '2026':
    - Jedi Knight II Mysteries of the Sith: reviews/2026/mysteriesofthesith.md
  - '2025':
    - Neva: reviews/2025/neva.md
    - Dredge: reviews/2025/dredge.md
    - Balatro: reviews/2025/balatro.md
    - Ghostunner II: reviews/2025/ghostrunner2.md
    - Helldivers 2: reviews/2025/helldivers2.md
    - Avatar Frontiers of Pandora: reviews/2025/avatarfrontiers.md
    - Warframe: reviews/2025/warframe.md
  - '2024':
    - Elden Ring: reviews/eldenring.md
    - Total War Warhammer III: reviews/totalwarwarhammeriii.md
    - A Plague Tale Requiem: reviews/plaguetalerequiem.md
    - Cocoon: reviews/Cocoon.mds
    - Halo Infinite: reviews/haloinfinite.md
    - Firewatch: reviews/firewatch.md
    - Against The Storm: reviews/againstthestorm.md
    - Ghostwire Tokyo: reviews/ghostwiretokyo.md
    - Metroid Dread: reviews/metroiddread.md
    - Deathloop: reviews/deathloop.md
    - Jedi Survivor: reviews/jedisurvivor.md
    - Hogwarts Legacy: reviews/hogwartslegacy.md
    - Vampire survivors: reviews/vampiresurvivors.md
    - Age of Mythology retold: reviews/ageofmythologyretold.md
    - Frostpunk 2: reviews/frostpunk2.md
    - Hi-Fi Rush: reviews/hifirush.md
    - Creatures of Ava: reviews/creaturesofava.md
    - Black Ops 6: reviews/blackops6.md
  - '2023':
    - Vanquish: reviews/vanquish.md
    - Divinity Original Sin 2: reviews/divinityostwo.md
    - Resident Evil Village: reviews/revillage.md
  - '2022':
    - 'Eventually'
  - '2021':
    - 'Eventually'

theme:
  name: dracula
  favicon: img/favicon.ico
  logo: img/favicon.png
